"use client";
import dynamic from "next/dynamic";
import { useMemo } from "react";

const map = {
  "contador-palabras": dynamic(() => import("./word-counter").then((m) => m.WordCounter), { ssr: false }),
  "contador-caracteres": dynamic(() => import("./character-counter").then((m) => m.CharacterCounter), { ssr: false }),
  "convertir-mayusculas": dynamic(() => import("./case-converter").then((m) => m.CaseConverter), { ssr: false }),
  "lorem-ipsum": dynamic(() => import("./lorem-ipsum").then((m) => m.LoremIpsum), { ssr: false }),
  "generador-passwords": dynamic(() => import("./password-generator").then((m) => m.PasswordGenerator), { ssr: false }),
  "generador-uuid": dynamic(() => import("./uuid-generator").then((m) => m.UuidGenerator), { ssr: false }),
  "generador-qr": dynamic(() => import("./qr-generator").then((m) => m.QrGenerator), { ssr: false }),
  "json-formatter": dynamic(() => import("./json-formatter").then((m) => m.JsonFormatter), { ssr: false }),
  "base64-encode": dynamic(() => import("./base64").then((m) => m.Base64Tool), { ssr: false }),
  "url-encode": dynamic(() => import("./url-encode").then((m) => m.UrlEncodeTool), { ssr: false }),
  "hash-md5-sha": dynamic(() => import("./hash-tool").then((m) => m.HashTool), { ssr: false }),
  "cps-test": dynamic(() => import("./cps-test").then((m) => m.CpsTest), { ssr: false }),
  "tiempo-reaccion": dynamic(() => import("./reaction-test").then((m) => m.ReactionTest), { ssr: false }),
  cronometro: dynamic(() => import("./stopwatch").then((m) => m.Stopwatch), { ssr: false }),
  "ruleta-decision": dynamic(() => import("./decision-wheel").then((m) => m.DecisionWheel), { ssr: false }),
  "unir-pdf": dynamic(() => import("./pdf-merge").then((m) => m.PdfMerge), { ssr: false }),
  "dividir-pdf": dynamic(() => import("./pdf-split").then((m) => m.PdfSplit), { ssr: false }),
  "rotar-pdf": dynamic(() => import("./pdf-rotate").then((m) => m.PdfRotate), { ssr: false }),
  "marca-agua-pdf": dynamic(() => import("./pdf-watermark").then((m) => m.PdfWatermark), { ssr: false }),
  "numerar-pdf": dynamic(() => import("./pdf-page-numbers").then((m) => m.PdfPageNumbers), { ssr: false }),
  "imagenes-a-pdf": dynamic(() => import("./jpg-to-pdf").then((m) => m.JpgToPdf), { ssr: false }),
  "proteger-pdf": dynamic(() => import("./pdf-protect").then((m) => m.PdfProtect), { ssr: false }),
  "informacion-pdf": dynamic(() => import("./pdf-info").then((m) => m.PdfInfo), { ssr: false }),
  "redimensionar-imagen": dynamic(() => import("./image-resize").then((m) => m.ImageResize), { ssr: false }),
  "comprimir-imagen": dynamic(() => import("./image-compress").then((m) => m.ImageCompress), { ssr: false }),
  "convertir-imagen": dynamic(() => import("./image-convert").then((m) => m.ImageConvert), { ssr: false }),
  "conversor-temperatura": dynamic(() => import("./temperature-converter").then((m) => m.TemperatureConverter), { ssr: false }),
  "conversor-unidades": dynamic(() => import("./unit-converter").then((m) => m.UnitConverter), { ssr: false }),
  "timestamp-converter": dynamic(() => import("./timestamp-converter").then((m) => m.TimestampConverter), { ssr: false }),
  "typing-test": dynamic(() => import("./typing-test").then((m) => m.TypingTest), { ssr: false }),
  temporizador: dynamic(() => import("./timer").then((m) => m.Timer), { ssr: false }),
  "numero-aleatorio": dynamic(() => import("./random-number").then((m) => m.RandomNumber), { ssr: false }),
  "cara-cruz": dynamic(() => import("./coin-flip").then((m) => m.CoinFlip), { ssr: false }),
  dados: dynamic(() => import("./dice-roller").then((m) => m.DiceRoller), { ssr: false }),
  "regex-tester": dynamic(() => import("./regex-tester").then((m) => m.RegexTester), { ssr: false }),
  "convertidor-color": dynamic(() => import("./color-converter").then((m) => m.ColorConverter), { ssr: false }),
  "texto-invertido": dynamic(() => import("./text-reverse").then((m) => m.TextReverse), { ssr: false }),
  "eliminar-acentos": dynamic(() => import("./remove-accents").then((m) => m.RemoveAccents), { ssr: false }),
  "generador-meta-tags": dynamic(() => import("./meta-tags-generator").then((m) => m.MetaTagsGenerator), { ssr: false }),
  "generador-robots": dynamic(() => import("./robots-generator").then((m) => m.RobotsGenerator), { ssr: false }),
  "densidad-keywords": dynamic(() => import("./keyword-density").then((m) => m.KeywordDensity), { ssr: false }),
  "previsualizador-serp": dynamic(() => import("./serp-preview").then((m) => m.SerpPreview), { ssr: false }),
  "generador-schema-faq": dynamic(() => import("./faq-schema-generator").then((m) => m.FaqSchemaGenerator), { ssr: false }),
  "generador-sitemap": dynamic(() => import("./sitemap-generator").then((m) => m.SitemapGenerator), { ssr: false }),
  "jwt-decoder": dynamic(() => import("./jwt-decoder").then((m) => m.JwtDecoder), { ssr: false }),
  "diff-checker": dynamic(() => import("./diff-checker").then((m) => m.DiffChecker), { ssr: false }),
  "css-formatter": dynamic(() => import("./css-formatter").then((m) => m.CssFormatter), { ssr: false }),
  "yaml-json-converter": dynamic(() => import("./yaml-json").then((m) => m.YamlJsonConverter), { ssr: false }),
  "prompt-builder": dynamic(() => import("./prompt-builder").then((m) => m.PromptBuilder), { ssr: false }),
  "contador-tokens": dynamic(() => import("./token-counter").then((m) => m.TokenCounter), { ssr: false }),
  "generador-titulos-seo": dynamic(() => import("./title-generator").then((m) => m.TitleGenerator), { ssr: false }),
  "plantillas-prompts": dynamic(() => import("./prompt-templates").then((m) => m.PromptTemplates), { ssr: false }),
  "firmar-pdf": dynamic(() => import("./pdf-sign").then((m) => m.PdfSign), { ssr: false }),
  "editar-pdf": dynamic(() => import("./pdf-edit").then((m) => m.PdfEdit), { ssr: false }),
  "reordenar-pdf": dynamic(() => import("./pdf-reorder").then((m) => m.PdfReorder), { ssr: false }),
  "pdf-a-jpg": dynamic(() => import("./pdf-to-jpg").then((m) => m.PdfToJpg), { ssr: false }),
  "comprimir-pdf": dynamic(() => import("./pdf-compress").then((m) => m.PdfCompress), { ssr: false }),
  "quitar-fondo-imagen": dynamic(() => import("./remove-background").then((m) => m.RemoveBackground), { ssr: false }),
  "recortar-imagen": dynamic(() => import("./image-crop").then((m) => m.ImageCrop), { ssr: false }),
  "marca-agua-imagen": dynamic(() => import("./image-watermark").then((m) => m.ImageWatermark), { ssr: false }),
  "analizador-meta": dynamic(() => import("./meta-analyzer").then((m) => m.MetaAnalyzer), { ssr: false }),
  "comparador-textos": dynamic(() => import("./plagio-comparador").then((m) => m.PlagioComparador), { ssr: false }),
  "whois-domain": dynamic(() => import("./whois-domain").then((m) => m.WhoisDomain), { ssr: false }),
  "dns-lookup": dynamic(() => import("./dns-lookup").then((m) => m.DnsLookup), { ssr: false }),
  "headers-checker": dynamic(() => import("./headers-checker").then((m) => m.HeadersChecker), { ssr: false }),
  "seo-quick-audit": dynamic(() => import("./seo-quick-audit").then((m) => m.SeoQuickAudit), { ssr: false })
} as const;

export function ToolRenderer({ slug }: { slug: string }) {
  const Component = useMemo(() => map[slug as keyof typeof map], [slug]);
  if (!Component) {
    return <div className="card text-center !py-10 text-[color:var(--color-fg-soft)]">🚧 Esta herramienta estará disponible muy pronto.</div>;
  }
  return <Component />;
}
